version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: hypothesis

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
