---
name: "Create PR to update job-server"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

jobs:
  create_job_server_pr:
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          repository: opensafely-core/job-server

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: interactive-templates-checkout

      - name: Read version file
        id: get-version
        run: |
          version=$(cat interactive-templates-checkout/version)
          echo "Will try to update to version: $version"
          echo "VERSION=v$version" >> "$GITHUB_OUTPUT"

          # remove interactive-templates-checkout so it doesn't get picked up
          # as a change to the job-server repo
          rm -rf interactive-templates-checkout

      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.11"

      - name: Update requirement to latest
        run: just update-interactive-templates ${{ steps.get-version.outputs.VERSION }}

      - name: Create a Pull Request if there are any changes
        id: create_pr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: "${{ secrets.JOB_SERVER_PR_TOKEN }}"
          branch: bot/update-interactive-templates
          commit-message: "feat: Update interactive templates to latest version"
          title: "Update interactive templates to latest version"
          body: "Update interative-templates to ${{ steps.get-version.outputs.VERSION }}"

      # untested
      #- name: Enable automerge
      #  if: steps.create_pr.outputs.pull-request-operation == 'created'
      #  env:
      #    GH_TOKEN: "${{ secrets.JOB_SERVER_PR_TOKEN }} "
      #  run: gh pr merge --merge --auto --squash ${{ steps.create_pr.outputs.pull-request-number }}
