---
name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.11"
          install-just: true
      - name: Check formatting, linting and import sorting
        run: just check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.11"
          install-just: true
      - name: Run tests
        run: just test

  test-package-build:
    runs-on: ubuntu-20.04

    name: Test we can build a Python package
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.11"
          install-just: true

      - name: Check the wheel installs and runs
        run: just package-test wheel

      - name: Check the sdist installs and runs
        run: just package-test sdist
